export const USER_LOGIN = "USER_LOGIN";
export const SET_SESSION_ID = "SET_SESSION_ID";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const CHANGE_CARTITEM_QUANTITY = "CHANGE_CARTITEM_QUANTITY";
